# docker build -t vv-backend:latest -f Dockerfile.backend .
# docker run -it -p 3000:3000 --rm vv-backend:latest 

FROM golang:1.19.4 as comp
RUN mkdir /builtfiles/
WORKDIR /temp/
COPY . .
RUN go build -o /builtfiles/ ./cmd/webapi

FROM debian:stable
WORKDIR /
COPY --from=comp /builtfiles/ .
EXPOSE 3000
CMD ["./webapi"]