# docker build -t vv-frontend:latest -f Dockerfile.frontend .
# docker run -it -p 8080:80 --rm vv-frontend:latest

FROM node:lts as comp
WORKDIR /src/webui
COPY webui .
RUN yarn run build-prod

FROM nginx:latest
COPY --from=comp /src/webui/dist /usr/share/nginx/html
EXPOSE 80